//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvdekiBakicim_WebAPI_CaseStudy.BusinessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public class JobAdvertisement
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Advertisement { get; set; }
        public string AdvertisementContent { get; set; }
    }
}
